---
title: "3rd Markdown Assignment"
author: "Gian Carlo Fernandez, John Kyle LLuz, Adrian Enrico Rodriguez, Iris Salangad"
date: "7/31/2021"
output:
  html_document:
    highlight: pygments
    theme: default
---

# An Effort to Lower Electricity Bill in University Building by Automatic Lighting Switches Application {.tabset .tabset-pills}

Martini Martini, Indra Riyanto, Adiyarta Krisna, M. Suparmoko

## Introduction

### **Introduction**

-----

As of writing this paper, the world is in hiatus from fully experiencing the world outside their homes.  In the midst of the COVID-19 pandemic, part of mitigating infection is the limitation of physical interactions among human beings.  With that, one solution set by the governments across various nations is putting their countries in quarantine.  While this certainly helps prevent the spread of the virus, there are other accompanying deficiencies in this solution beyond the virus.  One of which is the rise in household utility bills such as electricity.  During the pandemic, Filipino families have relied on electrically powered appliances such as air conditioners, televisions, and the like for comfort and entertainment.  With that, they also result in higher, sometimes unprecedented, electricity charges. 

<br>

Given this timely issue, solutions should be explored and implemented surrounding concepts of energy reduction and cost efficiency.  With that, the group came across an Indonesian academic article written by (authors) which tackles a simple yet impactful solution to  reducing the cost of electrical bills.  They identified that one of the most overlooked factors to heightened electricity bill prices is the constant usage of light bulbs and lamps.  Using fundamental concepts of electronics and programming, the researchers were able to test automatic light switches (sensor-based) against manual, traditional light switches in public restrooms as these are places wherein light is left on for long periods of time - therefore implying larger energy consumption and cost.
	
<br>

The study included 13 different samples depending on duration wherein the following essential data were obtained:  energy consumption with the sensor, energy consumption without the sensor, cost in Indonesian Rupiah (Rp) with the sensor, and the cost in Rp without the sensor.  However, the group ultimately decided to focus on energy consumption with the sensor as well as energy consumption without the sensor since conclusions regarding cost can immediately be drawn from these sets of data.  These were obtained by determining how much electrical power in kilowatt hour (kWh) was consumed at various fixed periods of time and comparing data with the sensor and with its absence.  In conclusion, the group would like to determine whether the application of sensor-based light switches can help decrease electricity consumption.

<br><br><br>

## Methodology

### **Methodology**

-----

content

## Results

### **Results**


-----

**Table for with sensors**



```{r}


Tws = data.frame( duration =        c(1,7,14,21,28,35,42,49,56,63,70,77,84),
                  with_sensor =  c(0.504, 2.711, 5.058, 7.158, 8.890, 10.622, 12.264, 13.816, 15.278,16.651,17.933, 19.126, 20.229),
                  energy_duration = c(24.10, 41.67, 45.59, 48.66, 52.18, 54.29,56.02, 57.54, 58.91, 60.20, 61.42, 62.59, 63.73))

Tws


y=c(1,7,14,21,28,35,42,49,56,63,70,77,84)
x=c(0.504, 2.711, 5.058, 7.158, 8.890, 10.622,                                          12.264, 13.816, 15.278,16.651,17.933, 19.126,                                      20.229)
z=c(24.10, 41.67, 45.59, 48.66, 52.18, 54.29,                                           56.02, 57.54, 58.91, 60.20, 61.42, 62.59,                                           63.73)


plot(x~y,
     main = "Energy Consumption WITH Sensors",
     xlab= "Duration (Hours)",
     ylab = "Electrical Power (kWh)",
     cex= 1,
     ylim = c(0, 60),
     col = "red",
     pch=21,  
     bg="red")

lines(x~y,
     bg="red")

line=lm(x~y)
abline(line, col="blue")


```

[yada yada]

```{r}
library(tidyverse)
library(DT)

iris %>%
  datatable(extensions = 'Buttons',
            options = list(dom = 'Blfrtip',
                           buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
                           lengthMenu = list(c(10,25,50,-1),
                                             c(10,25,50,"All"))))
```







**Table for without sensors**

```{r}
Twos = data.frame( duration =        c(1,7,14,21,28,35,42,49,56,63,70,77,84),
                  without_sensor =  c(0.664, 4.648, 9.296, 13.944, 18.592, 23.24,                                                                              27.888, 32.536, 37.184, 41.832, 46.48,                                                                                   51.128, 55.776 ), 
                  energy_duration = c(24.10, 41.67, 45.59, 48.66, 52.18, 54.29,                                                                                 56.02, 57.54, 58.91, 60.20, 61.42, 62.59,                                                                              63.73))

Twos

```

[yADA]
```{r}
y=c(1,7,14,21,28,35,42,49,56,63,70,77,84)
x=c(0.664, 4.648, 9.296, 13.944, 18.592, 23.24,                                         27.888, 32.536, 37.184, 41.832, 46.48,                                              51.128, 55.776 )
z=c(24.10, 41.67, 45.59, 48.66, 52.18, 54.29,                                           56.02, 57.54, 58.91, 60.20, 61.42, 62.59,                                           63.73)


plot(x~y,
     main = "Energy Consumption WITHOUT Sensors",
     xlab= "Duration (Hours)",
     ylab = "Electrical Power (kWh)",
     cex= 1,
     ylim = c(0, 60),
     col = "blue",
     pch=21,  
     bg="blue")

lines(x~y,
     bg="red")

line=lm(x~y)
abline(line, col="red")
```

**Comparison Based on the % of Reduction**


```{r}
a =  c(0.504, 2.711, 5.058, 7.158, 8.890, 10.622, 12.264, 13.816, 15.278,16.651,17.933, 19.126, 20.229)
b =  c(0.664, 4.648, 9.296, 13.944, 18.592, 23.24, 27.888, 32.536, 37.184, 41.832, 46.48,51.128, 55.776 )
 
 
 test = a/b
 
 
test2 = 1-test
  
test3=  test2*100


test3
 
 
```


```{r}



plot(test3~y,
     xlab="duration",
     ylab="Energy Reduction (%)",
     main= "Energy Reduction per week ",
      cex= 1,
     ylim = c(0, 65),
     col = "blue",
     pch=21,  
     bg="blue")
lines(test3~y,
     bg="blue")

line=lm(test3~y)
abline(line, col="red")

```




## Discussion and Conclusion


### **Discussion**

-----

content

### **Conclusion**

-----

content

## References

### **References**

-----

content